name: Publish

on: workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: npm install --ignore-scripts --production
    - run: npx node-pre-gyp configure --debug
      env:
        PKG_CONFIG_PATH:
    - run: npx node-pre-gyp build
    - run: npm install
    - run: npm test
    - run: npx @mapbox/node-pre-gyp package
    - run: npx @mmomtchev/node-pre-gyp-github publish
